spring.application.name=ApiGateway
server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

spring.cloud.gateway.server.webflux.routes[0].id=QuizService
spring.cloud.gateway.server.webflux.routes[0].uri=lb://QUIZSERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/quiz,/quiz/**

spring.cloud.gateway.server.webflux.routes[1].id=QuestionService
spring.cloud.gateway.server.webflux.routes[1].uri=lb://QUESTIONSERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/question,/question/**